"""initial schema

Revision ID: 531e052bb60d
Revises: 
Create Date: 2026-05-01 19:30:59.713084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '531e052bb60d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('setup', 'playing', 'scoring', 'finished')", name=op.f('ck_game_game_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('turn_order BETWEEN 1 AND 6', name=op.f('ck_player_player_turn_order_range')),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_player_game_id_game')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player')),
    sa.UniqueConstraint('game_id', 'color', name='uq_player_game_color'),
    sa.UniqueConstraint('game_id', 'name', name='uq_player_game_name'),
    sa.UniqueConstraint('game_id', 'turn_order', name='uq_player_game_turn_order')
    )
    op.create_table('score_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_undone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("event_type IN ('ROAD_COMPLETED', 'CITY_COMPLETED', 'MONASTERY_COMPLETED', 'ROAD_FINAL', 'CITY_FINAL', 'MONASTERY_FINAL', 'FARM_FINAL', 'MANUAL')", name=op.f('ck_score_action_score_action_event_type_check')),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_score_action_game_id_game')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_action'))
    )
    op.create_table('score_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('score_before', sa.Integer(), nullable=False),
    sa.Column('score_after', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['score_action.id'], name=op.f('fk_score_entry_action_id_score_action')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_score_entry_player_id_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_entry')),
    sa.UniqueConstraint('action_id', 'player_id', name='uq_score_entry_action_player')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_entry')
    op.drop_table('score_action')
    op.drop_table('player')
    op.drop_table('game')
    # ### end Alembic commands ###
